FROM dgarcia254/debian8-apache-sdk-cordova-quasar:latest

LABEL maintainer "Daniel Garcia - daniegarcia254@gmail.com"

#SET ENVIROMENT VARIABLES
ENV FRONT_DIR /usr/src/app/
RUN apt-get install vim -y

#Set the FRONTEND work directory
RUN mkdir -p /usr/src/app/
WORKDIR ${FRONT_DIR}

# Add our package.json and install *before* adding our FRONTEND app files
ADD client/package.json ./
RUN npm install

#Copy rest of the FRONTEND files and config env
COPY client /usr/src/app/

RUN npm run build
RUN cp -r dist /var/www/html/hattrick

#Start service
CMD ["/usr/sbin/apache2ctl","-D","FOREGROUND"]
