version: '3'
services:
  hattrick:
    container_name: hattrick
    restart: always
    links:
      - hattrick_db
    build:
      dockerfile: Dockerfile-back
      context: .
    expose:
      - "10002"
    ports:
      - "10002:10002"
    privileged: true
  hattrick_front:
    restart: always
    container_name: hattrick_front
    build:
      context: .
      dockerfile: Dockerfile-front
    expose:
      - "80"
    ports:
      - "10006:80"
    privileged: true
  hattrick_db:
    image: mysql:5.5
    restart: always
    container_name: hattrick_db
    privileged: true
    env_file:
      - mysql-environment.yml
